Repository umc-8th-Channeling/LLM, pull requests merged in 2025-08, with the labels that each got.

#37 REFACTOR : 댓글 분류 +요약 기능 구현
  core/llm/prompt_template_manager.py
  domain/comment/model/comment_type.py
  domain/comment/repository/__init__.py
  domain/comment/repository/comment_repository.py
  domain/comment/service/comment_service.py
  domain/comment/service/comments_service.py
  domain/report/repository/report_repository.py
  domain/report/service/report_consumer_impl.py
  domain/report/service/report_service.py
  external/rag/rag_service.py
  external/youtube/youtube_comment_service.py
Labels: :rainbow: 기능

#46 [REFACTOR]: 벌크 저장 구현
  core/database/repository/crud_repository.py
  domain/comment/repository/comment_repository.py
  domain/comment/service/comment_service.py
  domain/report/service/report_consumer_impl.py
  domain/report/service/report_service.py
Labels: 🛠️ 리팩토링

#38 [FEAT] 분석 - 알고리즘 최적화 방안
  core/config/database_config.py
  core/database/repository/vector_repository.py
  core/llm/prompt_template_manager.py
  domain/comment/model/comment.py
  domain/comment/model/comment_type.py
  domain/comment/service/comment_service.py
  domain/report/controller/report_controller.py
  domain/report/model/report.py
  domain/report/repository/report_repository.py
  domain/report/service/report_consumer_impl.py
  domain/report/service/report_service.py
  domain/video/service/video_service.py
  external/rag/chunk_service.py
  external/rag/leave_analyize.py
  external/rag/rag_service.py
  external/rag/rag_service_impl.py
  external/youtube/video_detail_service.py
  requirements.txt
Labels: :rainbow: 기능

#56 [BUG] 이탈 분석 타임아웃 에러 해결
  domain/report/controller/report_controller.py
  domain/report/service/report_consumer_impl.py
Labels: :rainbow: 기능, :bug: 버그

#53 [REFACTOR]: aws 환경 변수 제거, postgres 환경 변수 추가
  .github/workflows/CD.yml
  Dockerfile
Labels: :earth_americas: 인프라, 🛠️ 리팩토링

#61 [FEAT] 구글 액세스 토큰 입력 body에 추가
  core/kafka/message.py
  domain/report/controller/report_controller.py
  domain/report/service/report_consumer_impl.py
  external/rag/leave_analyize.py
Labels: :rainbow: 기능

#71 [FEAT]: 유튜브 스크립트 프록시 우회
  external/youtube/transcript_service.py
Labels: :rainbow: 기능, :bug: 버그

#73 [FIX] ip 필터링 제거
  external/youtube/transcript_service.py
Labels: :bug: 버그

#76 v1.0.5 프록시 환경 변수 CD에서 전달
  .github/workflows/CD.yml
Labels: :bug: 버그

#78 v1.0.6 ip 제한 아시아, 미국까지 확장
  external/youtube/transcript_service.py
Labels: :bug: 버그

#81 [FIX] 실시간 트렌드 키워드 파싱 오류 해결, 키워드 개수 6개 -> 5개로 수정
  core/llm/prompt_template_manager.py
  external/rag/rag_service_impl.py
Labels: :bug: 버그

#87 [FEAT] 영상과 유사한 이전 청크들을 context에 추가해 llm에 전달
  core/database/repository/vector_repository.py
  core/llm/prompt_template_manager.py
  domain/content_chunk/repository/content_chunk_repository.py
  domain/report/service/report_consumer_impl.py
  external/rag/rag_service_impl.py
Labels: 🛠️ 리팩토링

#88 [FEAT] kafka 메시지 발행 재시도 로직, consumer에서 예외 발생 시 status FAILED로 변경 로직 추가
  core/kafka/base_producer.py
  domain/report/service/report_consumer_impl.py
Labels: :rainbow: 기능, :bug: 버그

#89 [REFATCOR] 개요 페이지 리팩토링
  domain/comment/service/comment_service.py
  domain/report/service/report_consumer_impl.py
  domain/report/service/report_service.py
  domain/video/service/video_service.py
Labels: 🛠️ 리팩토링

#94 [REFACTOR] 분석 페이지 리팩토링
  domain/report/service/report_consumer_impl.py
  domain/report/service/report_service.py
Labels: 🛠️ 리팩토링

#97 v 1.2.0 전체 consumer 구조 리팩토링
  core/kafka/base_producer.py
  domain/comment/service/comment_service.py
  domain/report/service/report_consumer_impl.py
  domain/report/service/report_service.py
  domain/video/service/video_service.py
Labels: 🛠️ 리팩토링

#104 [FEAT] 한국 시간으로 저장되게 설정
  core/config/database_config.py
Labels: :bug: 버그

#113 v 1.2.3 키워드 응답 결과에서 백틱 제거
  README.md
  core/llm/prompt_template_manager.py
  external/rag/rag_service_impl.py
Labels: :bug: 버그, :earth_americas: 인프라

#117 [FEAT] 자막을 못 가져오는 영상의 경우 에러가 아닌, 내부 처리로 수정
  external/rag/leave_analyize.py
  external/rag/rag_service_impl.py
Labels: 🛠️ 리팩토링

#124 v 1.2.7 rich 의존성 패키지 삭제
  domain/video/service/video_service.py
Labels: :bug: 버그

#126 [CHORE] 데이터 저장할 때 한국 시간으로 저장
  core/kafka/base_producer.py
  core/utils/datetime_utils.py
  domain/channel/model/channel.py
  domain/comment/model/comment.py
  domain/idea/model/idea.py
  domain/report/model/report.py
  domain/trend_keyword/model/trend_keyword.py
Labels: 🛠️ 리팩토링

#127 v 1.2.8 데이터 저장할 때 한국 시간으로 저장
  core/kafka/base_producer.py
  core/utils/datetime_utils.py
  domain/channel/model/channel.py
  domain/comment/model/comment.py
  domain/idea/model/idea.py
  domain/report/model/report.py
  domain/trend_keyword/model/trend_keyword.py
Labels: 🛠️ 리팩토링

#128 v 1.2.9 우회 ip 국가 한국, 일본으로 제한
  external/youtube/transcript_service.py
Labels: :earth_americas: 인프라, 🛠️ 리팩토링
